"use client";

import React from 'react';
import { Brain, Sparkles, Target, Rocket, Gamepad } from 'lucide-react';

const loadingSteps = [
  "Firing up the neural networks...",
  "Calibrating cosmic alignment (it helps, trust us).",
  "Crafting your personalized quest about FutureTech...",
  "Adding a pinch of unexpected difficulty...",
  "AI is brewing your unique challenge...",
];

const AnimatedDot = ({ color, style }: { color: string; style?: React.CSSProperties }) => (
  <span
    style={style}
    className={`inline-block w-2.5 h-2.5 rounded-full ${color} animate-pulse mx-1`}
  ></span>
);

const LoadingScreen = () => {
  const [currentStepIndex, setCurrentStepIndex] = React.useState(0);

  React.useEffect(() => {
    const interval = setInterval(() => {
      setCurrentStepIndex(prev => (prev + 1) % loadingSteps.length);
    }, 3000);
    return () => clearInterval(interval);
  }, []);

  const currentStatus = loadingSteps[currentStepIndex];

  return (
    <div className="flex items-center justify-center min-h-screen p-4 
       transition-colors duration-300">
      
      <div className="w-full max-w-md p-8 
        bg-white dark:bg-gray-800 
        rounded-3xl shadow-2xl border border-gray-200/60 dark:border-gray-700/60 
        transition-all duration-300 relative overflow-hidden">

        {/* Glow Effects */}
        <div className="absolute inset-0 z-0 opacity-10">
          <div className="absolute -top-16 -left-16 w-32 h-32 
            bg-indigo-300 dark:bg-indigo-900 
            rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob"></div>

          <div className="absolute -bottom-16 -right-16 w-32 h-32 
            bg-sky-300 dark:bg-sky-900
            rounded-full mix-blend-multiply filter blur-xl opacity-70 animate-blob animation-delay-2000"></div>
        </div>

        <div className="relative z-10 text-center">
          {/* Animated Brain Icon */}
          <div className="inline-flex p-4 rounded-full shadow-lg mb-6 
            bg-gradient-to-br from-indigo-500 to-fuchsia-500 animate-spin-slow">
            <Brain className="w-8 h-8 text-white" />
          </div>

          {/* Title */}
          <h1 className="text-3xl font-extrabold tracking-tight mb-8 
            text-indigo-700 dark:text-indigo-300 flex items-center justify-center">
            <Sparkles className="w-6 h-6 mr-2 text-yellow-400" />
            AI Magic in Progress
          </h1>

          {/* Did You Know Box */}
          <div className="p-6 mb-8 rounded-2xl
            bg-sky-50 dark:bg-sky-900/40
            border-2 border-sky-200/50 dark:border-sky-700/50 
            shadow-inner">

            <p className="text-xl font-bold 
              text-indigo-700 dark:text-indigo-300 mb-2 
              flex items-center justify-center">
              <Sparkles className="w-5 h-5 mr-1 text-yellow-500" />
              Did you know?
              <Sparkles className="w-5 h-5 ml-1 text-yellow-500" />
            </p>

            <p className="text-sm text-gray-700 dark:text-gray-300 leading-relaxed">
              Every player gets 
              <span className="font-semibold text-indigo-600 dark:text-indigo-400">
                {" "}unique challenges
              </span> 
              generated by the model! 
              No two quests are the same.
              <Target className="inline-block w-4 h-4 ml-1 text-red-500" />
            </p>
          </div>

          {/* Status */}
          <div className="mt-8 text-left">
            <p className="text-lg font-medium 
              text-gray-800 dark:text-gray-200 
              mb-4 flex items-center">
              <Rocket className="w-5 h-5 mr-3 text-red-500" />
              <span className="truncate">{currentStatus}</span>
            </p>

            {/* Dots */}
            <div className="flex justify-center items-center mt-6">
              <AnimatedDot color="bg-pink-500" />
              <AnimatedDot color="bg-indigo-500" style={{ animationDelay: "0.2s" }} />
              <AnimatedDot color="bg-sky-500" style={{ animationDelay: "0.4s" }} />
              <AnimatedDot color="bg-yellow-500" style={{ animationDelay: "0.6s" }} />
            </div>

            {/* Progress Text */}
            <p className="mt-6 text-sm italic 
              text-gray-500 dark:text-gray-400 
              flex items-center justify-center">
              <Gamepad className="w-4 h-4 mr-2" />
              Preparing the Game World...
            </p>
          </div>

        </div>
      </div>
    </div>
  );
};

export default LoadingScreen;
